import { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Modal, Pressable, ScrollView, Share, StyleSheet, Text, TextInput, View } from 'react-native';
import { mobileApi } from '../src/api';
import { useMobileAuth } from '../src/auth';
import { colors, common } from '../src/theme';

type Session = {_id:string;userAgent?:string;ip?:string;createdAt:string;expiresAt:string};
type ExportData = {exportedAt:string;user:unknown;posts:unknown[];reels:unknown[];comments:unknown[];follows:unknown[];conversations:unknown[];messages:unknown[];calls:unknown[];reports:unknown[]};

export default function AccountSecurity(){
  const {user,logout}=useMobileAuth();
  const [sessions,setSessions]=useState<Session[]|null>(null);
  const [message,setMessage]=useState('');
  const [error,setError]=useState('');
  const [busy,setBusy]=useState(false);
  const [deleteOpen,setDeleteOpen]=useState(false);
  const [password,setPassword]=useState('');

  const load=async()=>{try{setSessions(await mobileApi<Session[]>('/api/auth/sessions'))}catch(reason){setError(reason instanceof Error?reason.message:'Could not load sessions')}};
  useEffect(()=>{void load()},[]);

  const revoke=async(session:Session)=>{try{await mobileApi(`/api/sessions/${session._id}`,{method:'DELETE'});setSessions(old=>old?.filter(value=>value._id!==session._id)??null)}catch(reason){setError(reason instanceof Error?reason.message:'Could not revoke this session')}};
  const resend=async()=>{try{await mobileApi('/api/auth/resend-verification',{method:'POST'});setMessage('A new verification link was requested.')}catch(reason){setError(reason instanceof Error?reason.message:'Could not resend verification')}};
  const exportData=async()=>{setBusy(true);setError('');try{const data=await mobileApi<ExportData>('/api/account/export');const summary=`InstaFrame data export\nPrepared: ${new Date(data.exportedAt).toLocaleString()}\nPosts: ${data.posts.length}\nReels: ${data.reels.length}\nComments: ${data.comments.length}\nConnections: ${data.follows.length}\nConversations: ${data.conversations.length}\nMessages sent: ${data.messages.length}\nCalls: ${data.calls.length}\nReports: ${data.reports.length}\n\nFull JSON export follows:\n${JSON.stringify(data,null,2)}`;await Share.share({title:'My InstaFrame data',message:summary});setMessage('Your private data export is ready to save or share.')}catch(reason){setError(reason instanceof Error?reason.message:'Could not prepare your data')}finally{setBusy(false)}};
  const deleteAccount=async()=>{if(!password){setError('Enter your password to confirm account deletion.');return}setBusy(true);setError('');try{await mobileApi('/api/account/delete',{method:'POST',body:JSON.stringify({password})});setDeleteOpen(false);setPassword('');await logout()}catch(reason){setError(reason instanceof Error?reason.message:'Could not delete account')}finally{setBusy(false)}};
  const requestDelete=()=>Alert.alert('Delete your account?','Your profile will be anonymized, sessions revoked, discovery data removed, content hidden and media cleanup queued. This cannot be undone.',[{text:'Cancel',style:'cancel'},{text:'Continue',style:'destructive',onPress:()=>setDeleteOpen(true)}]);

  if(!sessions)return <ActivityIndicator style={{marginTop:70}} color={colors.green}/>;
  return <ScrollView style={common.screen} contentContainerStyle={s.screen} keyboardShouldPersistTaps="handled">
    <Text style={common.eyebrow}>ACCOUNT SECURITY</Text><Text style={common.title}>Devices & account</Text>
    <View style={s.email}><View><Text style={s.emailTitle}>Email verification</Text><Text style={s.emailState}>{user?.emailVerified?'Verified':'Verification required'}</Text></View>{!user?.emailVerified&&<Pressable style={s.resend} onPress={()=>void resend()}><Text style={s.resendText}>Resend link</Text></Pressable>}</View>
    {!!message&&<Text style={s.success}>{message}</Text>}{!!error&&<Text style={s.error}>{error}</Text>}
    <Text style={s.heading}>Active sessions</Text><Text style={s.copy}>Revoke devices you do not recognize. These details are visible only to you.</Text>
    {sessions.map(session=><View style={s.session} key={session._id}><View style={s.device}><Text style={s.deviceIcon}>Device</Text></View><View style={s.sessionCopy}><Text numberOfLines={2} style={s.agent}>{session.userAgent??'Unknown device'}</Text><Text style={s.meta}>{session.ip??'Unknown network'} · expires {new Date(session.expiresAt).toLocaleDateString()}</Text></View><Pressable onPress={()=>void revoke(session)}><Text style={s.revoke}>Revoke</Text></Pressable></View>)}
    {!sessions.length&&<Text style={common.muted}>No active sessions.</Text>}
    <Text style={s.heading}>Your information</Text><View style={s.dataCard}><Text style={s.cardTitle}>Download My Data</Text><Text style={s.copy}>Prepare a private JSON copy of your profile and activity. Choose a trusted destination when sharing.</Text><Pressable disabled={busy} style={s.dataButton} onPress={()=>void exportData()}><Text style={s.dataButtonText}>{busy?'Preparing...':'Prepare data export'}</Text></Pressable></View>
    <View style={s.dangerCard}><Text style={s.dangerTitle}>Delete account</Text><Text style={s.copy}>Permanently anonymizes your profile, invalidates every session, removes discovery indexing and queues media deletion.</Text><Pressable style={s.deleteButton} onPress={requestDelete}><Text style={s.deleteText}>Permanently delete account</Text></Pressable></View>
    <Modal visible={deleteOpen} transparent animationType="slide" onRequestClose={()=>setDeleteOpen(false)}><View style={s.backdrop}><View style={s.sheet}><Text style={s.dangerTitle}>Final confirmation</Text><Text style={s.copy}>Enter your password. This action cannot be reversed.</Text><TextInput value={password} onChangeText={setPassword} secureTextEntry autoCapitalize="none" placeholder="Password" style={s.input}/>{!!error&&<Text style={s.error}>{error}</Text>}<Pressable disabled={busy||!password} style={[s.confirmDelete,(!password||busy)&&s.disabled]} onPress={()=>void deleteAccount()}><Text style={s.confirmText}>{busy?'Deleting...':'Delete my account'}</Text></Pressable><Pressable style={s.cancel} onPress={()=>{setDeleteOpen(false);setPassword('')}}><Text>Cancel</Text></Pressable></View></View></Modal>
  </ScrollView>
}

const s=StyleSheet.create({screen:{padding:22,paddingBottom:90},email:{backgroundColor:'white',borderWidth:1,borderColor:colors.line,borderRadius:14,padding:15,marginTop:20,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},emailTitle:{fontWeight:'800',color:colors.ink},emailState:{fontSize:12,color:colors.muted,marginTop:4},resend:{backgroundColor:'#e5ece7',padding:9,borderRadius:9},resendText:{color:colors.green,fontWeight:'800',fontSize:11},success:{color:colors.green,backgroundColor:'#e8f3ed',padding:10,borderRadius:9,marginTop:12},error:{color:colors.danger,backgroundColor:'#fff0ee',padding:10,borderRadius:9,marginTop:12},heading:{fontSize:18,fontWeight:'900',color:colors.ink,marginTop:25},copy:{color:colors.muted,lineHeight:19,marginVertical:8},session:{flexDirection:'row',alignItems:'center',gap:11,backgroundColor:'white',padding:13,borderBottomWidth:1,borderColor:colors.line},device:{width:46,height:40,borderRadius:12,backgroundColor:'#e5ece7',alignItems:'center',justifyContent:'center'},deviceIcon:{color:colors.green,fontSize:9,fontWeight:'800'},sessionCopy:{flex:1},agent:{fontWeight:'700',color:colors.ink,fontSize:12},meta:{fontSize:10,color:colors.muted,marginTop:4},revoke:{color:colors.danger,fontWeight:'800',fontSize:11},dataCard:{backgroundColor:'white',borderWidth:1,borderColor:colors.line,borderRadius:15,padding:16,marginTop:10},cardTitle:{fontSize:16,fontWeight:'900',color:colors.ink},dataButton:{backgroundColor:colors.green,padding:12,borderRadius:10,alignItems:'center',marginTop:8},dataButtonText:{color:'white',fontWeight:'900'},dangerCard:{backgroundColor:'#fff5f3',borderWidth:1,borderColor:'#f2cec8',borderRadius:15,padding:16,marginTop:18},dangerTitle:{fontSize:17,fontWeight:'900',color:colors.danger},deleteButton:{borderWidth:1,borderColor:colors.danger,padding:12,borderRadius:10,alignItems:'center',marginTop:8},deleteText:{color:colors.danger,fontWeight:'900'},backdrop:{flex:1,backgroundColor:'rgba(0,0,0,.58)',justifyContent:'flex-end'},sheet:{backgroundColor:'white',borderTopLeftRadius:24,borderTopRightRadius:24,padding:22},input:{borderWidth:1,borderColor:colors.line,borderRadius:11,padding:13,marginTop:10},confirmDelete:{backgroundColor:colors.danger,padding:14,borderRadius:11,alignItems:'center',marginTop:14},confirmText:{color:'white',fontWeight:'900'},disabled:{opacity:.45},cancel:{alignItems:'center',padding:14}});
