import { Link,useRouter } from 'expo-router';
import { useMemo,useState,type ComponentProps } from 'react';
import { ActivityIndicator,KeyboardAvoidingView,Platform,ScrollView,StyleSheet,Text,TextInput,TouchableOpacity,View } from 'react-native';
import { useMobileAuth } from './auth';
import { colors,common } from './theme';

export function AuthScreen({mode}:{mode:'login'|'register'}){
  const auth=useMobileAuth();const router=useRouter();
  const [name,setName]=useState('');const [username,setUsername]=useState('');const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [showPassword,setShowPassword]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  const valid=useMemo(()=>email.trim().includes('@')&&password.length>=10&&(mode==='login'||(name.trim().length>=2&&/^[a-zA-Z0-9._]{3,30}$/.test(username))),[email,password,mode,name,username]);
  const submit=async()=>{if(!valid||busy)return;setBusy(true);setError('');try{if(mode==='login')await auth.login(email.trim(),password);else await auth.register({name:name.trim(),username:username.trim().toLowerCase(),email:email.trim(),password});router.replace('/(tabs)')}catch(e){setError(e instanceof Error?e.message:'Could not continue. Please try again.')}finally{setBusy(false)}};
  return <KeyboardAvoidingView style={s.screen} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={s.content}><View style={s.hero}><Text style={s.brand}>▣  InstaFrame</Text><Text style={s.heroTitle}>Share what feels{`\n`}like you.</Text><Text style={s.heroCopy}>A private-by-design place to connect, create and belong.</Text><View style={s.trust}><Text style={s.trustText}>Discovery is off until you choose it</Text></View></View><View style={s.form}><Text style={common.eyebrow}>{mode==='login'?'WELCOME BACK':'YOUR STORY STARTS HERE'}</Text><Text style={s.heading}>{mode==='login'?'Sign in to your frame':'Create your account'}</Text><Text style={s.subheading}>{mode==='login'?'Pick up where you left off.':'Build your profile and start sharing your moments.'}</Text>{mode==='register'&&<><Field label="Full name" value={name} onChangeText={setName} placeholder="Aria Kapoor" autoComplete="name"/><Field label="Username" value={username} onChangeText={setUsername} placeholder="aria.k" autoCapitalize="none" autoCorrect={false}/></>}<Field label="Email address" value={email} onChangeText={setEmail} placeholder="you@example.com" autoCapitalize="none" keyboardType="email-address" autoComplete="email"/><Text style={s.label}>Password</Text><View style={s.passwordRow}><TextInput style={s.passwordInput} value={password} onChangeText={setPassword} secureTextEntry={!showPassword} placeholder="At least 10 characters" autoCapitalize="none" autoComplete={mode==='login'?'current-password':'new-password'} accessibilityLabel="Password"/><TouchableOpacity accessibilityRole="button" accessibilityLabel={showPassword?'Hide password':'Show password'} onPress={()=>setShowPassword(value=>!value)}><Text style={s.show}>{showPassword?'Hide':'Show'}</Text></TouchableOpacity></View>{mode==='login'&&<Link href="/forgot-password" style={s.forgot}>Forgot password?</Link>}{!!error&&<Text accessibilityLiveRegion="polite" style={s.error}>{error}</Text>}<TouchableOpacity accessibilityRole="button" style={[common.button,(!valid||busy)&&s.disabled]} disabled={!valid||busy} onPress={()=>void submit()}>{busy?<ActivityIndicator color="white"/>:<Text style={common.buttonText}>{mode==='login'?'Sign in':'Create account'}</Text>}</TouchableOpacity><View style={s.switchRow}><Text style={s.switch}>{mode==='login'?'New to InstaFrame?':'Already a member?'}</Text><Link href={mode==='login'?'/register':'/login'} asChild><TouchableOpacity accessibilityRole="button" style={s.switchButton}><Text style={s.link}>{mode==='login'?'Create account':'Sign in'}</Text></TouchableOpacity></Link></View><Text style={s.legal}>By continuing, you agree to the Terms and acknowledge the Privacy Policy.</Text></View></ScrollView></KeyboardAvoidingView>
}
type FieldProps=ComponentProps<typeof TextInput>&{label:string};function Field({label,...props}:FieldProps){return <View><Text style={s.label}>{label}</Text><TextInput {...props} style={s.input} accessibilityLabel={label}/></View>}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:colors.bg},content:{flexGrow:1,paddingBottom:48},hero:{backgroundColor:colors.green,paddingHorizontal:28,paddingTop:42,paddingBottom:24,minHeight:210},brand:{color:'white',fontWeight:'900',fontSize:18},heroTitle:{color:'white',fontWeight:'900',fontSize:37,lineHeight:43,marginTop:30},heroCopy:{color:'#d5e2dc',fontSize:15,lineHeight:22,marginTop:10,maxWidth:315},trust:{alignSelf:'flex-start',backgroundColor:'rgba(255,255,255,.12)',borderRadius:20,paddingHorizontal:12,paddingVertical:7,marginTop:17},trustText:{color:'#eef5f1',fontSize:12,fontWeight:'700'},form:{padding:24,gap:10},heading:{fontSize:28,fontWeight:'900',color:colors.ink},subheading:{color:colors.muted,lineHeight:20,marginBottom:8},label:{fontSize:13,fontWeight:'700',color:colors.ink,marginBottom:6},input:{backgroundColor:'white',borderWidth:1,borderColor:colors.line,borderRadius:13,paddingHorizontal:14,paddingVertical:13,color:colors.ink,fontSize:15},passwordRow:{flexDirection:'row',alignItems:'center',backgroundColor:'white',borderWidth:1,borderColor:colors.line,borderRadius:13,paddingRight:14},passwordInput:{flex:1,paddingHorizontal:14,paddingVertical:13,color:colors.ink,fontSize:15},show:{color:colors.green,fontWeight:'800'},forgot:{alignSelf:'flex-end',color:colors.green,fontWeight:'700',marginBottom:3},error:{color:colors.danger,backgroundColor:'#fff0ee',padding:11,borderRadius:9},disabled:{opacity:.48},switchRow:{flexDirection:'row',justifyContent:'center',alignItems:'center',gap:7,marginTop:8},switch:{color:colors.muted},switchButton:{paddingVertical:10,paddingHorizontal:4},link:{color:colors.green,fontWeight:'800'},legal:{fontSize:11,lineHeight:17,textAlign:'center',color:colors.muted,marginTop:5,paddingHorizontal:12}});

