import type { MessageDto } from '@instaframe/contracts';
import { useRouter } from 'expo-router';
import { useEffect,useRef,useState } from 'react';
import { Image,Pressable,StyleSheet,Text,View } from 'react-native';
import { useMobileAuth } from './auth';
import { getMobileSocket } from './socket';
import { colors } from './theme';
export function MessageBanner(){const {user}=useMobileAuth(),router=useRouter(),[message,setMessage]=useState<MessageDto>(),timer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);useEffect(()=>{if(!user)return;const socket=getMobileSocket(),incoming=(item:MessageDto)=>{if(item.sender.id===user.id)return;setMessage(item);if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>setMessage(undefined),5000)};socket.on('message:new',incoming);return()=>{socket.off('message:new',incoming);if(timer.current)clearTimeout(timer.current)}},[user?.id]);if(!message)return null;const open=()=>{setMessage(undefined);router.push({pathname:'/messages/[id]',params:{id:message.conversationId,title:message.sender.name}})};return <View pointerEvents="box-none" style={s.layer}><Pressable accessibilityLabel={`New message from ${message.sender.name}`} onPress={open} style={s.banner}>{message.sender.profilePhoto?<Image source={{uri:message.sender.profilePhoto}} style={s.avatar}/>:<View style={s.fallback}><Text style={s.initial}>{message.sender.name[0]}</Text></View>}<View style={s.copy}><View style={s.top}><Text numberOfLines={1} style={s.name}>{message.sender.name}</Text><Text style={s.now}>now</Text></View><Text numberOfLines={1} style={s.text}>{message.text||'Sent an attachment'}</Text></View><Pressable accessibilityLabel="Dismiss message" hitSlop={10} onPress={()=>setMessage(undefined)}><Text style={s.close}>×</Text></Pressable></Pressable></View>}
const s=StyleSheet.create({layer:{position:'absolute',top:12,left:12,right:12,zIndex:1000,elevation:30},banner:{backgroundColor:'white',borderRadius:17,padding:11,flexDirection:'row',alignItems:'center',gap:10,borderWidth:1,borderColor:colors.line,shadowColor:'#000',shadowOpacity:.18,shadowRadius:14,shadowOffset:{width:0,height:5},elevation:12},avatar:{width:44,height:44,borderRadius:22},fallback:{width:44,height:44,borderRadius:22,backgroundColor:'#dce9e2',alignItems:'center',justifyContent:'center'},initial:{fontWeight:'900',color:colors.green},copy:{flex:1},top:{flexDirection:'row',alignItems:'center'},name:{fontWeight:'900',color:colors.ink,flex:1},now:{fontSize:10,color:colors.muted},text:{color:colors.muted,marginTop:3},close:{fontSize:22,color:colors.muted,padding:3}});
