import argon2 from 'argon2';import crypto from 'node:crypto';import jwt,{type SignOptions} from 'jsonwebtoken';import { env } from '../config/env.js';import { AppError } from '../middleware/error.js';import { AuthToken,Session,User } from '../models/index.js';import { deliverAuthLink,type AuthMailKind } from './email.js';import { recoveryCodeHash,verifyMfaCode } from './mfa.js';
const publicUser=(u:{_id:unknown;name:string;username:string;email:string;emailVerifiedAt?:Date;verified:boolean;isPrivate:boolean;allowPhotoDiscovery:boolean;profilePhoto?:string;role:string;followersCount:number;followingCount:number;postsCount:number})=>({id:String(u._id),name:u.name,username:u.username,email:u.email,emailVerified:Boolean(u.emailVerifiedAt),verified:u.verified,isPrivate:u.isPrivate,allowPhotoDiscovery:u.allowPhotoDiscovery,profilePhoto:u.profilePhoto,role:u.role,followersCount:u.followersCount,followingCount:u.followingCount,postsCount:u.postsCount});
const access=(u:{_id:unknown;username:string;role:string},mfaVerified=false)=>jwt.sign({sub:String(u._id),username:u.username,role:u.role,type:'access',mfaVerified},env.JWT_SECRET,{expiresIn:env.ACCESS_TOKEN_TTL as SignOptions['expiresIn']});const digest=(token:string)=>crypto.createHash('sha256').update(token).digest('hex');
export async function register(input:{name:string;username:string;email:string;password:string},meta:{userAgent?:string;ip?:string}){if(await User.exists({$or:[{email:input.email.toLowerCase()},{username:input.username.toLowerCase()}]}))throw new AppError(409,'ACCOUNT_EXISTS','Email or username is already in use');const user=await User.create({...input,email:input.email.toLowerCase(),username:input.username.toLowerCase(),passwordHash:await argon2.hash(input.password)});try{await sendAuthToken(user._id,user.email,'email_verification',24*60)}catch(error){console.error('Verification email could not be sent after registration',error instanceof Error?error.message:'unknown email error')}return issue(user,meta)}
export async function login(email:string,password:string,meta:{userAgent?:string;ip?:string},mfaCode?:string){const user=await User.findOne({email:email.toLowerCase()}).select('+email +passwordHash +emailVerifiedAt +mfaSecretEncrypted +mfaRecoveryCodeHashes');if(!user||!await argon2.verify(user.passwordHash,password)||user.status!=='active')throw new AppError(401,'INVALID_CREDENTIALS','Invalid email or password');let mfaVerified=Boolean(user.mfaEnabled&&mfaCode&&/^\d{6}$/.test(mfaCode)&&user.mfaSecretEncrypted&&await verifyMfaCode(user.mfaSecretEncrypted,mfaCode));if(user.mfaEnabled&&!mfaVerified&&mfaCode&&!/^\d{6}$/.test(mfaCode)){const hash=recoveryCodeHash(mfaCode);mfaVerified=Boolean(await User.findOneAndUpdate({_id:user._id,mfaRecoveryCodeHashes:hash},{$pull:{mfaRecoveryCodeHashes:hash}}))}if(user.mfaEnabled&&!mfaVerified)throw new AppError(401,'MFA_REQUIRED','A valid authenticator or recovery code is required');return issue(user,meta,mfaVerified)}
async function issue(user:typeof User.prototype,meta:{userAgent?:string;ip?:string},mfaVerified=false){const token=crypto.randomBytes(48).toString('base64url');const expiresAt=new Date(Date.now()+env.REFRESH_TOKEN_TTL_DAYS*86400000);const session=await Session.create({userId:user._id,refreshTokenHash:digest(token),mfaVerified,userAgent:meta.userAgent,ip:meta.ip,expiresAt});return{user:{...publicUser(user),mfaVerified},accessToken:access(user,mfaVerified),refreshToken:`${session._id}.${token}`,expiresAt}}
export async function rotate(raw:string,meta:{userAgent?:string;ip?:string}){const [id,token]=raw.split('.');if(!id||!token)throw new AppError(401,'INVALID_REFRESH','Refresh token is invalid');const session=await Session.findById(id).select('+refreshTokenHash');const hash=digest(token);if(!session||session.revokedAt||session.expiresAt<new Date()||!crypto.timingSafeEqual(Buffer.from(hash),Buffer.from(session.refreshTokenHash))){if(session)await Session.updateMany({userId:session.userId,revokedAt:null},{$set:{revokedAt:new Date()}});throw new AppError(401,'INVALID_REFRESH','Refresh token is invalid')}session.revokedAt=new Date();await session.save();const user=await User.findById(session.userId).select('+email +emailVerifiedAt');if(!user)throw new AppError(401,'INVALID_REFRESH','Account no longer exists');return issue(user,meta,session.mfaVerified)}
export async function revoke(raw?:string){if(!raw)return;const [id]=raw.split('.');if(id)await Session.findByIdAndUpdate(id,{revokedAt:new Date()})}
async function sendAuthToken(userId:unknown,email:string,purpose:AuthMailKind,minutes:number){const now=new Date();await AuthToken.updateMany({userId,purpose,usedAt:null},{$set:{usedAt:now}});const token=crypto.randomBytes(40).toString('base64url');await AuthToken.create({userId,purpose,tokenHash:digest(token),expiresAt:new Date(Date.now()+minutes*60000)});await deliverAuthLink({to:email,kind:purpose,token})}
export async function requestPasswordReset(email:string){const user=await User.findOne({email:email.toLowerCase(),status:'active'}).select('+email');if(user)await sendAuthToken(user._id,user.email,'password_reset',30)}
export async function resetPassword(token:string,password:string){const record=await AuthToken.findOne({purpose:'password_reset',tokenHash:digest(token),usedAt:null,expiresAt:{$gt:new Date()}}).select('+tokenHash');if(!record)throw new AppError(400,'INVALID_RESET_TOKEN','Reset link is invalid or expired');const now=new Date();await Promise.all([User.findByIdAndUpdate(record.userId,{$set:{passwordHash:await argon2.hash(password)}}),Session.updateMany({userId:record.userId,revokedAt:null},{$set:{revokedAt:now}}),AuthToken.updateMany({userId:record.userId,usedAt:null},{$set:{usedAt:now}})])}
export async function verifyEmail(token:string){const record=await AuthToken.findOne({purpose:'email_verification',tokenHash:digest(token),usedAt:null,expiresAt:{$gt:new Date()}}).select('+tokenHash');if(!record)throw new AppError(400,'INVALID_VERIFICATION_TOKEN','Verification link is invalid or expired');const now=new Date();await Promise.all([User.findByIdAndUpdate(record.userId,{$set:{emailVerifiedAt:now}}),AuthToken.updateMany({userId:record.userId,purpose:'email_verification',usedAt:null},{$set:{usedAt:now}})])}
export async function resendVerification(userId:string){const user=await User.findById(userId).select('+email +emailVerifiedAt');if(!user||user.emailVerifiedAt)return;await sendAuthToken(user._id,user.email,'email_verification',24*60)}
