import { AppError } from '../middleware/error.js';import {AccountRestriction,Block,Call,CallParticipant,Follow,PlatformSetting,User} from '../models/index.js';import {messagePermission} from './messaging.js';
export async function expireCalls(){const now=new Date(),expired=await Call.find({status:{$in:['initiating','ringing']},ringExpiresAt:{$lte:now}}).select('_id');if(!expired.length)return 0;const ids=expired.map(c=>c._id);await Promise.all([Call.updateMany({_id:{$in:ids}},{$set:{status:'missed',endedAt:now,endedReason:'missed'}}),CallParticipant.updateMany({callId:{$in:ids},status:{$in:['invited','ringing']}},{$set:{status:'missed',leftAt:now}})]);return ids.length}
export async function canCall(callerId:string,targetId:string,kind:'audio'|'video'){
 if(callerId===targetId)throw new AppError(400,'INVALID_CALLEE','Invalid call recipient');await expireCalls();
 const [caller,target,blocked,restricted]=await Promise.all([User.findOne({_id:callerId,status:'active'}).select('_id').lean(),User.findOne({_id:targetId,status:'active'}).select('privacy').lean(),Block.exists({$or:[{blocker:callerId,blocked:targetId},{blocker:targetId,blocked:callerId}]}),AccountRestriction.exists({userId:callerId,kind:'messaging',active:true,$or:[{endsAt:null},{endsAt:{$gt:new Date()}}]})]);
 if(!caller)throw new AppError(403,'CALLER_UNAVAILABLE','Your account cannot place calls');if(!target)throw new AppError(404,'USER_NOT_FOUND','User not found');if(blocked)throw new AppError(403,'INTERACTION_BLOCKED','Calling is unavailable between blocked accounts');if(restricted)throw new AppError(403,'CALL_RESTRICTED','Calling is temporarily restricted');if(kind==='video'&&target.privacy?.allowVideoCalls===false)throw new AppError(403,'VIDEO_CALLS_DISABLED','This member is not accepting video calls');
 const policy=String(target.privacy?.whoCanCall??'followers');if(policy==='none')throw new AppError(403,'CALLS_DISABLED','This member is not accepting calls');const [callerFollows,targetFollows]=await Promise.all([Follow.exists({follower:callerId,following:targetId,status:'accepted'}),Follow.exists({follower:targetId,following:callerId,status:'accepted'})]);
 const allowed=policy==='everyone'||policy==='following'&&targetFollows||policy==='followers'&&callerFollows||policy==='mutuals'&&callerFollows&&targetFollows||policy==='message_eligible'&&await messagePermission(callerId,targetId).then(()=>true).catch(()=>false);if(!allowed)throw new AppError(403,'CALL_NOT_ALLOWED','This member does not accept calls from you');
 const busy=await Call.exists({status:{$in:['initiating','ringing','accepted','active']},$or:[{caller:targetId},{callee:targetId}]});if(busy)throw new AppError(409,'USER_BUSY','This member is currently busy');return target;
}
export async function ensureCallParticipant(callId:string,userId:string){const call=await Call.findById(callId);if(!call||![String(call.caller),String(call.callee)].includes(userId))throw new AppError(404,'CALL_NOT_FOUND','Call not found');if(await Block.exists({$or:[{blocker:call.caller,blocked:call.callee},{blocker:call.callee,blocked:call.caller}]})){if(!['ended','missed','rejected','declined','failed'].includes(call.status)){call.status='ended';call.endedAt=new Date();call.endedReason='blocked';await call.save()}throw new AppError(403,'INTERACTION_BLOCKED','Calling is unavailable between blocked accounts')}return call}
