import { createHash } from 'node:crypto';
import { env } from '../config/env.js';
import { Notification,NotificationPreference,PushToken } from '../models/index.js';

export type NotificationType='like'|'comment'|'reply'|'mention'|'follow'|'follow_request'|'follow_accepted'|'message'|'message_request'|'group_invite'|'group_join_request'|'group_mention'|'call'|'final_note'|'story_reaction'|'story_mention'|'reel_like'|'reel_comment'|'security_alert'|'moderation_notice'|'appeal_outcome'|'verification_outcome'|'system_announcement'|'admin';
type Category='follows'|'likes'|'comments'|'mentions'|'stories'|'reels'|'messages'|'messageRequests'|'finalNotes'|'securityAlerts'|'moderation'|'productUpdates';
const categories:Record<NotificationType,Category>={like:'likes',comment:'comments',reply:'comments',mention:'mentions',follow:'follows',follow_request:'follows',follow_accepted:'follows',message:'messages',message_request:'messageRequests',group_invite:'messages',group_join_request:'messages',group_mention:'mentions',call:'messages',final_note:'finalNotes',story_reaction:'stories',story_mention:'stories',reel_like:'reels',reel_comment:'reels',security_alert:'securityAlerts',moderation_notice:'moderation',appeal_outcome:'moderation',verification_outcome:'moderation',system_announcement:'productUpdates',admin:'moderation'};
const critical=new Set<NotificationType>(['security_alert','moderation_notice']);
const safePayload=(value:Record<string,unknown>={})=>Object.fromEntries(Object.entries(value).filter(([key,item])=>/^(route|targetId|targetType|count|action|conversationId|postId|reelId|storyId)$/.test(key)&&(['string','number','boolean'].includes(typeof item))));
type PreferenceShape={quietHours?:{enabled?:boolean;timezone?:string;start?:string;end?:string};messagePreview?:string}&Partial<Record<Category,{inApp?:boolean;push?:boolean}>>;
const inQuietHours=(preference:PreferenceShape|null,now=new Date())=>{if(!preference?.quietHours?.enabled)return false;try{const parts=new Intl.DateTimeFormat('en-GB',{timeZone:preference.quietHours.timezone,hour:'2-digit',minute:'2-digit',hour12:false}).format(now).split(':').map(Number);const current=(parts[0]??0)*60+(parts[1]??0);const parse=(v:string)=>{const [h,m]=v.split(':').map(Number);return(h??0)*60+(m??0)};const start=parse(preference.quietHours.start??'22:00'),end=parse(preference.quietHours.end??'07:00');return start>end?current>=start||current<end:current>=start&&current<end}catch{return false}};

export interface PushProvider{send(token:string,platform:string,payload:{title:string;body:string;data:Record<string,unknown>}):Promise<'sent'|'invalid'|'failed'>}
export class HttpPushProvider implements PushProvider{async send(token:string,platform:string,payload:{title:string;body:string;data:Record<string,unknown>}){if(!env.PUSH_PROVIDER_URL||!env.PUSH_PROVIDER_API_KEY)return'failed' as const;try{const response=await fetch(env.PUSH_PROVIDER_URL,{method:'POST',headers:{authorization:`Bearer ${env.PUSH_PROVIDER_API_KEY}`,'content-type':'application/json'},body:JSON.stringify({token,platform,...payload}),signal:AbortSignal.timeout(5000)});return response.status===404||response.status===410?'invalid':response.ok?'sent':'failed'}catch{return'failed'}}}

export async function notify(input:{recipient:unknown;actor?:unknown;type:NotificationType;post?:unknown;comment?:unknown;targetType?:string;targetId?:string;titleKey?:string;bodyKey?:string;payloadSafe?:Record<string,unknown>;eventKey?:string},provider:PushProvider=new HttpPushProvider()){
  if(input.actor&&String(input.recipient)===String(input.actor))return null;
  const preference=await NotificationPreference.findOne({userId:input.recipient}).lean() as PreferenceShape|null;const category=categories[input.type];const setting=preference?.[category];const mustDeliver=critical.has(input.type);
  let notification:unknown=null;if(setting?.inApp!==false||mustDeliver){const document={...input,payloadSafe:safePayload(input.payloadSafe)};if(input.eventKey){const id=createHash('sha256').update(`${input.recipient}:${input.eventKey}`).digest('hex').slice(0,24);notification=await Notification.findOneAndUpdate({_id:id},{$setOnInsert:{_id:id,...document}},{upsert:true,new:true,setDefaultsOnInsert:true})}else notification=await Notification.create(document)}
  if((setting?.push!==false||mustDeliver)&&(!inQuietHours(preference)||mustDeliver)){const tokens=await PushToken.find({userId:input.recipient,revokedAt:null}).select('+token');const privateType=input.type==='message'||input.type==='final_note';const body=privateType&&preference?.messagePreview!=='show'?(input.type==='message'?'New message':'New final note'):(input.bodyKey??'You have a new notification');await Promise.all(tokens.map(async token=>{const result=await provider.send(token.token,token.platform,{title:input.titleKey??'InstaFrame',body,data:safePayload(input.payloadSafe)});if(result==='invalid')await PushToken.updateOne({_id:token._id},{$set:{revokedAt:new Date()}})}))}
  return notification;
}
export const tokenFingerprint=(token:string)=>createHash('sha256').update(token).digest('hex').slice(0,16);
