import crypto from 'node:crypto';import { isValidObjectId,Types } from 'mongoose';
import { Block,Follow,FollowRequest,User } from '../models/index.js';
import { AppError } from '../middleware/error.js';

export const publicUserFields='name username profilePhoto verified verificationStatus isPrivate followersCount followingCount postsCount';
export const followRelationId=(follower:unknown,following:unknown)=>new Types.ObjectId(crypto.createHash('sha256').update(`${String(follower)}:${String(following)}`).digest('hex').slice(0,24));
export function assertOtherUser(viewerId:string,targetId:string){if(!isValidObjectId(targetId)||viewerId===targetId)throw new AppError(400,'INVALID_USER','Choose another valid member');}
export async function isBlockedEitherWay(a:unknown,b:unknown){return Boolean(await Block.exists({$or:[{blocker:a,blocked:b},{blocker:b,blocked:a}]}));}
export async function assertInteractionAllowed(a:unknown,b:unknown){if(await isBlockedEitherWay(a,b))throw new AppError(403,'INTERACTION_BLOCKED','This interaction is unavailable');}
export async function canViewProfileContent(viewerId:string,targetId:string){if(viewerId===targetId)return true;if(await isBlockedEitherWay(viewerId,targetId))return false;const target=await User.findOne({_id:targetId,status:'active'}).select('isPrivate').lean();if(!target)return false;if(!target.isPrivate)return true;return Boolean(await Follow.exists({follower:viewerId,following:targetId,status:'accepted'}));}
export async function relationshipState(viewerId:string,targetId:string){if(viewerId===targetId)return {state:'self' as const,isFollowedByViewer:false,followsViewer:false};if(await isBlockedEitherWay(viewerId,targetId))return {state:'blocked' as const,isFollowedByViewer:false,followsViewer:false};const [following,request,reverse]=await Promise.all([Follow.exists({follower:viewerId,following:targetId,status:'accepted'}),FollowRequest.exists({requester:viewerId,target:targetId,status:'pending'}),Follow.exists({follower:targetId,following:viewerId,status:'accepted'})]);return {state:following?'following' as const:request?'pending' as const:reverse?'follow_back' as const:'none' as const,isFollowedByViewer:Boolean(following),followsViewer:Boolean(reverse)};}
export async function reconcileFollowCounters(ids:unknown[]){const unique=[...new Set(ids.map(String))];await Promise.all(unique.map(async id=>{const [followersCount,followingCount]=await Promise.all([Follow.countDocuments({following:id,status:'accepted'}),Follow.countDocuments({follower:id,status:'accepted'})]);await User.updateOne({_id:id},{$set:{followersCount,followingCount}});}));}
