import { Router,type Response } from 'express';import { env } from '../config/env.js';import { requireAuth } from '../middleware/auth.js';import { requireTrustedWebOrigin } from '../middleware/csrf.js';import { AppError } from '../middleware/error.js';import { Session,User } from '../models/index.js';import * as auth from '../services/auth.js';import { encryptMfaSecret,generateRecoveryCodes,newMfaSetup,verifyMfaCode } from '../services/mfa.js';import { credentialsSchema,forgotPasswordSchema,mfaCodeSchema,registrationSchema,resetPasswordSchema,verifyEmailSchema } from '../validators/auth.js';
const router=Router();const cookie={httpOnly:true,secure:env.COOKIE_SECURE,sameSite:'strict' as const,path:'/api/auth',maxAge:env.REFRESH_TOKEN_TTL_DAYS*86400000};const mobile=(headers:Record<string,unknown>)=>headers['x-instaframe-client']==='mobile';
function respond(res:Response,result:Awaited<ReturnType<typeof auth.login>>,status=200,isMobile=false){if(!isMobile)res.cookie('refreshToken',result.refreshToken,cookie);return res.status(status).json({success:true,data:{user:result.user,accessToken:result.accessToken,...(isMobile?{refreshToken:result.refreshToken}:{})}})}
router.post('/register',async(req,res)=>{const result=await auth.register(registrationSchema.parse(req.body),{userAgent:req.get('user-agent'),ip:req.ip});return respond(res,result,201,mobile(req.headers))});
router.post('/login',async(req,res)=>{const input=credentialsSchema.parse(req.body);const result=await auth.login(input.email,input.password,{userAgent:req.get('user-agent'),ip:req.ip},input.mfaCode);return respond(res,result,200,mobile(req.headers))});
router.post('/refresh',requireTrustedWebOrigin,async(req,res)=>{const isMobile=mobile(req.headers);const result=await auth.rotate(String(isMobile?req.body?.refreshToken:req.cookies.refreshToken??''),{userAgent:req.get('user-agent'),ip:req.ip});return respond(res,result,200,isMobile)});
router.post('/logout',requireTrustedWebOrigin,async(req,res)=>{const isMobile=mobile(req.headers);await auth.revoke(isMobile?req.body?.refreshToken:req.cookies.refreshToken);if(!isMobile)res.clearCookie('refreshToken',{path:'/api/auth'});res.json({success:true,data:null})});
router.post('/mfa/setup',requireAuth,async(req,res)=>{const user=await User.findById(req.user!.id).select('+email +mfaSecretEncrypted');if(!user||user.role==='USER')throw new AppError(403,'FORBIDDEN','Administrator role required');if(user.mfaEnabled)throw new AppError(409,'MFA_ALREADY_ENABLED','MFA is already enabled');const setup=newMfaSetup(user.email);user.mfaSecretEncrypted=encryptMfaSecret(setup.secret);await user.save();res.json({success:true,data:setup})});
router.post('/mfa/confirm',requireAuth,async(req,res)=>{const {code}=mfaCodeSchema.parse(req.body);const user=await User.findById(req.user!.id).select('+mfaSecretEncrypted +mfaRecoveryCodeHashes');if(!user||user.role==='USER'||!user.mfaSecretEncrypted)throw new AppError(400,'MFA_SETUP_REQUIRED','Start MFA setup first');if(!await verifyMfaCode(user.mfaSecretEncrypted,code))throw new AppError(400,'INVALID_MFA_CODE','Authenticator code is invalid');const recovery=generateRecoveryCodes();user.mfaEnabled=true;user.mfaRecoveryCodeHashes=recovery.hashes;await user.save();await Session.updateMany({userId:user._id,revokedAt:null},{$set:{revokedAt:new Date()}});res.json({success:true,data:{enabled:true,reloginRequired:true,recoveryCodes:recovery.codes}})});
router.post('/forgot-password',async(req,res)=>{const {email}=forgotPasswordSchema.parse(req.body);await auth.requestPasswordReset(email);res.status(202).json({success:true,data:null,message:'If an active account exists, a reset link has been sent.'})});
router.post('/reset-password',async(req,res)=>{const input=resetPasswordSchema.parse(req.body);await auth.resetPassword(input.token,input.password);res.json({success:true,data:null,message:'Password reset successfully. Sign in again on every device.'})});
router.post('/verify-email',async(req,res)=>{const {token}=verifyEmailSchema.parse(req.body);await auth.verifyEmail(token);res.json({success:true,data:null,message:'Email address verified.'})});
router.post('/resend-verification',requireAuth,async(req,res)=>{await auth.resendVerification(req.user!.id);res.status(202).json({success:true,data:null,message:'If verification is still required, a new link has been sent.'})});
router.get('/sessions',requireAuth,async(req,res)=>{const sessions=await Session.find({userId:req.user!.id,revokedAt:null}).select('userAgent ip createdAt expiresAt').lean();res.json({success:true,data:sessions})});export default router;
