import { Router } from 'express';import { isValidObjectId } from 'mongoose';import { requireAuth } from '../middleware/auth.js';import { AppError } from '../middleware/error.js';import { Block,Follow,Reel,ReelBookmark,ReelComment,ReelLike,ReelWatch,User } from '../models/index.js';import { assertMediaPublishable } from '../services/mediaSafety.js';import { notify } from '../services/notifications.js';import { canAccessReel,requireReel } from '../services/reels.js';import { mentionsFromPost } from '../validators/post.js';import { hashtagsFrom,reelCommentSchema,reelCreateSchema,reelWatchSchema } from '../validators/reel.js';
import crypto from 'node:crypto';import { Types } from 'mongoose';
export const reelRouter=Router();reelRouter.use(requireAuth);const authorFields='name username profilePhoto verified isPrivate followersCount followingCount postsCount';
const compatibleVideoUrl=(url:string)=>url.includes('/res.cloudinary.com/')&&url.includes('/video/upload/')?url.replace('/video/upload/','/video/upload/f_mp4,vc_h264,ac_aac,q_auto:good/'):url;
const mapReel=(item:Record<string,unknown>,liked:Set<string>,saved:Set<string>)=>{const video=item.video as {secureUrl?:string}|undefined;return{...item,video:video?.secureUrl?{...video,secureUrl:compatibleVideoUrl(video.secureUrl)}:video,id:String(item._id),_id:undefined,isLiked:liked.has(String(item._id)),isSaved:saved.has(String(item._id))}};
reelRouter.get('/reels',async(req,res)=>{const limit=Math.min(Math.max(Number(req.query.limit)||10,1),20),cursor=typeof req.query.cursor==='string'&&isValidObjectId(req.query.cursor)?req.query.cursor:undefined,mode=req.query.feed==='following'?'following':'recommended';const [following,blocks]=await Promise.all([Follow.find({follower:req.user!.id,status:'accepted'}).distinct('following'),Block.find({$or:[{blocker:req.user!.id},{blocked:req.user!.id}]}).select('blocker blocked').lean()]),blocked=blocks.map(row=>String(row.blocker)===req.user!.id?row.blocked:row.blocker);const query={processingStatus:'ready',deletedAt:null,author:{$nin:blocked,...(mode==='following'?{$in:following}:{})},$or:[{visibility:'public'},{visibility:'followers',author:{$in:following}},{author:req.user!.id}],...(cursor?{_id:{$lt:cursor}}:{})};const items=await Reel.find(query).sort(mode==='recommended'?{viewsCount:-1,watchTimeMs:-1,_id:-1}:{_id:-1}).limit(limit*3).populate('author',authorFields).lean(),visible=[];for(const item of items)if(await canAccessReel(req.user!.id,item))visible.push(item);const page=visible.slice(0,limit),ids=page.map(i=>i._id),[likes,saves]=await Promise.all([ReelLike.find({user:req.user!.id,reel:{$in:ids}}).distinct('reel'),ReelBookmark.find({user:req.user!.id,reel:{$in:ids}}).distinct('reel')]);res.set('Cache-Control','private, max-age=10');res.json({success:true,data:{items:page.map(i=>mapReel(i as Record<string,unknown>,new Set(likes.map(String)),new Set(saves.map(String)))),nextCursor:visible.length>limit?String(page.at(-1)?._id):null,feed:mode}});});
reelRouter.post('/reels',async(req,res)=>{const input=reelCreateSchema.parse(req.body);if(!input.video.publicId.startsWith(`instaframe/${req.user!.id}/reels/`))throw new AppError(400,'INVALID_MEDIA_OWNER','Reel media does not belong to this account');await assertMediaPublishable([input.video.publicId]);const usernames=mentionsFromPost(input.caption),mentioned=await User.find({username:{$in:usernames},status:'active'}).select('_id').lean();const reel=await Reel.create({...input,author:req.user!.id,hashtags:hashtagsFrom(input.caption),mentions:mentioned.map(x=>x._id),originalStoragePath:input.video.publicId,processedVideoPath:input.video.publicId,processingStatus:input.draft?'processing':'ready',publishedAt:input.draft?undefined:new Date()});await Promise.all(mentioned.map(x=>notify({recipient:x._id,actor:req.user!.id,type:'mention'})));res.status(201).json({success:true,data:{...reel.toObject(),id:String(reel._id)}});});
reelRouter.get('/reels/:id',async(req,res)=>{const reel=await requireReel(req.user!.id,req.params.id);await reel.populate('author',authorFields);res.json({success:true,data:{...reel.toObject(),id:String(reel._id)}});});
reelRouter.post('/reels/:id/view',async(req,res)=>{const reel=await requireReel(req.user!.id,req.params.id),result=await ReelWatch.updateOne({user:req.user!.id,reel:reel._id,sessionId:`view-${req.user!.id}`},{$setOnInsert:{user:req.user!.id,reel:reel._id,sessionId:`view-${req.user!.id}`,watchedMs:250}},{upsert:true});if(result.upsertedCount)await Reel.updateOne({_id:reel._id},{$inc:{viewsCount:1}});res.json({success:true,data:null});});
reelRouter.post('/reels/:id/watch',async(req,res)=>{const input=reelWatchSchema.parse(req.body),reel=await requireReel(req.user!.id,req.params.id),id=new Types.ObjectId(crypto.createHash('sha256').update(`${req.user!.id}:${reel._id}:${input.sessionId}`).digest('hex').slice(0,24)),result=await ReelWatch.updateOne({_id:id},{$setOnInsert:{_id:id,user:req.user!.id,reel:reel._id,...input}},{upsert:true});if(result.upsertedCount)await Reel.updateOne({_id:reel._id},{$inc:{watchTimeMs:input.watchedMs,completionCount:input.completed?1:0,viewsCount:1}});res.json({success:true,data:{recorded:true}});});
for(const [path,Model,count] of [['like',ReelLike,'likesCount'],['save',ReelBookmark,'savesCount']] as const){reelRouter.post(`/reels/:id/${path}`,async(req,res)=>{const reel=await requireReel(req.user!.id,req.params.id),result=await Model.updateOne({user:req.user!.id,reel:reel._id},{$setOnInsert:{user:req.user!.id,reel:reel._id}},{upsert:true});if(result.upsertedCount)await Reel.updateOne({_id:reel._id},{$set:{[count]:await Model.countDocuments({reel:reel._id})}});if(path==='like'&&result.upsertedCount)await notify({recipient:reel.author,actor:req.user!.id,type:'like'});res.json({success:true,data:{active:true}})});reelRouter.delete(`/reels/:id/${path}`,async(req,res)=>{const removed=await Model.findOneAndDelete({user:req.user!.id,reel:req.params.id});if(removed)await Reel.updateOne({_id:req.params.id},{$set:{[count]:await Model.countDocuments({reel:req.params.id})}});res.json({success:true,data:{active:false}})});}
reelRouter.get('/reels/:id/comments',async(req,res)=>{const reel=await requireReel(req.user!.id,req.params.id),items=await ReelComment.find({reel:reel._id,deletedAt:null}).sort({_id:-1}).limit(50).populate('author',authorFields).lean();res.json({success:true,data:{items}})});
reelRouter.post('/reels/:id/comments',async(req,res)=>{const input=reelCommentSchema.parse(req.body),reel=await requireReel(req.user!.id,req.params.id);if(!reel.commentsEnabled)throw new AppError(403,'COMMENTS_DISABLED','Comments are disabled');const comment=await ReelComment.create({reel:reel._id,author:req.user!.id,body:input.body,parent:input.parentId});await Reel.updateOne({_id:reel._id},{$inc:{commentsCount:1}});await notify({recipient:reel.author,actor:req.user!.id,type:'comment'});res.status(201).json({success:true,data:{...comment.toObject(),id:String(comment._id)}})});
reelRouter.post('/reels/:id/share',async(req,res)=>{const reel=await requireReel(req.user!.id,req.params.id);await Reel.updateOne({_id:reel._id},{$inc:{sharesCount:1}});res.json({success:true,data:{shared:true,shareUrl:`/reels/${reel._id}`}})});
