import {Router} from 'express';
import {Types} from 'mongoose';
import {z} from 'zod';
import {requireAuth} from '../middleware/auth.js';
import {AccountProfile,Block,Follow,Hashtag,Interest,Post,RecentSearch,Reel,SearchAnalytics,SearchProfile,User,UserInterest} from '../models/index.js';
import {diverseRank,diversifyByCreator,escapeRegex,normalizeSearch,textRelevance} from '../services/ranking.js';

export const searchRouter=Router();searchRouter.use(requireAuth);
const userFields='name username bio location profilePhoto verified isPrivate allowProfileDiscovery allowPhotoDiscovery followersCount followingCount postsCount accountType profession organization createdAt';
const authorFields='name username profilePhoto verified isPrivate allowProfileDiscovery followersCount followingCount postsCount accountType';
const types=['all','people','posts','reels','hashtags','creators','businesses'] as const;
const interestSeeds=[['technology','Technology'],['coding','Coding'],['gaming','Gaming'],['education','Education'],['science','Science'],['business','Business'],['sports','Sports'],['music','Music'],['photography','Photography'],['travel','Travel'],['fashion','Fashion'],['fitness','Fitness'],['art','Art']] as const;
const mapUser=(value:Record<string,unknown>)=>({...value,id:String(value._id),_id:undefined});
const mapContent=(value:Record<string,unknown>)=>({...value,id:String(value._id),_id:undefined});
async function blockedIds(userId:string){const rows=await Block.find({$or:[{blocker:userId},{blocked:userId}]}).select('blocker blocked').lean();return rows.map(row=>String(row.blocker)===userId?row.blocked:row.blocker)}
async function ensureInterests(){await Interest.bulkWrite(interestSeeds.map(([key,displayName],displayOrder)=>({updateOne:{filter:{key},update:{$setOnInsert:{key,displayName,active:true,displayOrder}},upsert:true}})),{ordered:false})}
async function indexCandidates(ids:unknown[]){if(!ids.length)return;const [users,profiles]=await Promise.all([User.find({_id:{$in:ids}}).select('name username profession organization accountType allowProfileDiscovery status updatedAt').lean(),AccountProfile.find({userId:{$in:ids}}).select('userId businessName businessCategory creatorCategory accountType').lean()]);await SearchProfile.bulkWrite(users.map(user=>{const professional=profiles.find(item=>String(item.userId)===String(user._id)),terms=[user.name,user.username,user.profession,user.organization,professional?.businessName,professional?.businessCategory,professional?.creatorCategory].filter(Boolean).flatMap(value=>normalizeSearch(String(value)).split(' ')).filter(value=>value.length>1);return{updateOne:{filter:{userId:user._id},update:{$set:{normalizedUsername:normalizeSearch(user.username),normalizedDisplayName:normalizeSearch(user.name),normalizedBusinessName:normalizeSearch(professional?.businessName??''),searchTerms:[...new Set(terms)],accountType:professional?.accountType??user.accountType,category:professional?.businessCategory??professional?.creatorCategory,discoverable:user.status==='active'&&user.allowProfileDiscovery!==false,lastActiveAt:user.updatedAt}},upsert:true}}}),{ordered:false})}

searchRouter.get('/search',async(req,res)=>{const q=String(req.query.q??'').trim().slice(0,80),normalized=normalizeSearch(q),type=types.includes(String(req.query.type) as typeof types[number])?String(req.query.type) as typeof types[number]:'all',limit=Math.min(30,Math.max(1,Number(req.query.limit)||20)),cursor=String(req.query.cursor??''),blocked=await blockedIds(req.user!.id),excluded=[new Types.ObjectId(req.user!.id),...blocked],cursorFilter=Types.ObjectId.isValid(cursor)?{_id:{$lt:new Types.ObjectId(cursor)}}:{};if(normalized.length<2)return res.json({success:true,data:{users:[],posts:[],reels:[],hashtags:[],creators:[],businesses:[],suggestions:[],nextCursor:null}});
 const prefix=new RegExp(`^${escapeRegex(normalized)}`,'i'),contains=new RegExp(escapeRegex(normalized),'i');
 const candidates=await User.find({_id:{$nin:excluded},status:'active',...cursorFilter,$or:[{username:prefix},{name:contains},{profession:contains},{organization:contains},{location:contains}]}).select(userFields).limit(80).lean();
 const accountProfiles=await AccountProfile.find({userId:{$in:candidates.map(item=>item._id)},$or:[{businessName:contains},{businessCategory:contains},{creatorCategory:contains}]}).lean();const professionalIds=accountProfiles.map(item=>item.userId);
 const fuzzy=normalized.length>=4?await User.find({_id:{$nin:[...excluded,...candidates.map(item=>item._id)]},status:'active',username:new RegExp(`^${escapeRegex(normalized.slice(0,1))}`,'i')}).select(userFields).limit(80).lean():[];
 const combined=[...candidates,...fuzzy,...(professionalIds.length?await User.find({_id:{$in:professionalIds,$nin:excluded},status:'active'}).select(userFields).lean():[])],unique=[...new Map(combined.map(item=>[String(item._id),item])).values()];await indexCandidates(unique.map(item=>item._id));
 const follows=await Follow.find({follower:req.user!.id,status:'accepted'}).distinct('following'),viewerFollowing=new Set(follows.map(String));const followerRows=await Follow.find({following:req.user!.id,status:'accepted'}).distinct('follower'),mutualBase=await Follow.find({follower:{$in:followerRows},status:'accepted'}).select('following').lean(),mutualCounts=new Map<string,number>();mutualBase.forEach(item=>mutualCounts.set(String(item.following),(mutualCounts.get(String(item.following))??0)+1));
 const scored=unique.map(user=>{const professional=accountProfiles.find(item=>String(item.userId)===String(user._id)),areaMatch=user.location&&normalizeSearch(user.location).includes(normalized)?45:0;return{user,professional,score:textRelevance(normalized,{username:user.username,name:user.name,businessName:professional?.businessName??undefined,category:professional?.businessCategory??professional?.creatorCategory??undefined})+areaMatch+(viewerFollowing.has(String(user._id))?12:0)+Math.min(15,(mutualCounts.get(String(user._id))??0)*3)+(user.verified?4:0)}}).filter(item=>item.score>=25).sort((a,b)=>b.score-a.score);
 const users=type==='posts'||type==='reels'||type==='hashtags'?[]:scored.slice(0,limit).map(item=>mapUser(item.user as unknown as Record<string,unknown>)),creators=type==='all'||type==='creators'?scored.filter(item=>(item.professional?.accountType??item.user.accountType)==='creator').slice(0,limit).map(item=>mapUser(item.user as unknown as Record<string,unknown>)):[],businesses=type==='all'||type==='businesses'?scored.filter(item=>(item.professional?.accountType??item.user.accountType)==='business').slice(0,limit).map(item=>({...mapUser(item.user as unknown as Record<string,unknown>),businessName:item.professional?.businessName,businessCategory:item.professional?.businessCategory})):[];
 const contentQuery={$or:[{caption:contains},{hashtags:normalized}],visibility:'public',deletedAt:null};const [posts,reels,hashtags]=await Promise.all([type==='people'||type==='reels'||type==='hashtags'||type==='creators'||type==='businesses'?[]:Post.find({...contentQuery,archivedAt:null,author:{$nin:blocked}}).sort({likesCount:-1,createdAt:-1}).limit(limit).populate('author',authorFields).lean(),type==='people'||type==='posts'||type==='hashtags'||type==='creators'||type==='businesses'?[]:Reel.find({...contentQuery,processingStatus:'ready',author:{$nin:blocked}}).sort({viewsCount:-1,likesCount:-1,publishedAt:-1}).limit(limit).populate('author',authorFields).lean(),type==='people'||type==='posts'||type==='reels'||type==='creators'||type==='businesses'?[]:Hashtag.find({normalizedTag:prefix}).sort({usageCount:-1}).limit(15).lean()]);
 const total=users.length+posts.length+reels.length+hashtags.length+creators.length+businesses.length;await Promise.all([RecentSearch.findOneAndUpdate({userId:req.user!.id,normalizedQuery:normalized,resultType:type},{$set:{query:q,createdAt:new Date()}},{upsert:true}),SearchAnalytics.updateOne({normalizedQuery:normalized,resultType:type},{$inc:{searches:1,zeroResults:total?0:1},$set:{lastSearchedAt:new Date()}},{upsert:true})]);res.set('Cache-Control','private, max-age=10');res.json({success:true,data:{users,posts:posts.map(item=>mapContent(item as unknown as Record<string,unknown>)),reels:reels.map(item=>mapContent(item as unknown as Record<string,unknown>)),hashtags:hashtags.map(item=>({name:item.displayTag??item.normalizedTag,count:item.usageCount})),creators,businesses,suggestions:[...new Set([...scored.slice(0,5).map(item=>item.user.username),...hashtags.slice(0,5).map(item=>`#${item.normalizedTag}`)])],nextCursor:scored.length>limit?String(scored[limit-1]?.user._id):null}})});

searchRouter.get('/search/suggestions',async(req,res)=>{const q=normalizeSearch(String(req.query.q??'').slice(0,80)),blocked=await blockedIds(req.user!.id),[users,tags,trending]=await Promise.all([q.length<1?[]:User.find({_id:{$nin:[req.user!.id,...blocked]},status:'active',username:new RegExp(`^${escapeRegex(q)}`,'i')}).select('username name profilePhoto verified').limit(7).lean(),q.length<1?[]:Hashtag.find({normalizedTag:new RegExp(`^${escapeRegex(q)}`,'i')}).sort({usageCount:-1}).limit(7).lean(),q.length?[]:SearchAnalytics.find({zeroResults:{$lt:5}}).sort({searches:-1,lastSearchedAt:-1}).limit(8).lean()]);res.json({success:true,data:{people:users.map(item=>mapUser(item as unknown as Record<string,unknown>)),hashtags:tags.map(item=>({name:item.normalizedTag,count:item.usageCount})),trending:trending.map(item=>({query:item.normalizedQuery,count:item.searches}))}})});
searchRouter.get('/search/recent',async(req,res)=>{const items=await RecentSearch.find({userId:req.user!.id}).sort({updatedAt:-1}).limit(15).select('query resultType updatedAt').lean();res.json({success:true,data:{items:items.map(item=>({id:String(item._id),query:item.query,type:item.resultType,updatedAt:item.updatedAt}))}})});searchRouter.delete('/search/recent',async(req,res)=>{await RecentSearch.deleteMany({userId:req.user!.id});res.json({success:true,data:{cleared:true}})});
searchRouter.get('/interests',async(req,res)=>{await ensureInterests();const [items,selected]=await Promise.all([Interest.find({active:true}).sort({displayOrder:1}).lean(),UserInterest.find({userId:req.user!.id}).distinct('interestId')]);res.json({success:true,data:{items:items.map(item=>({id:String(item._id),key:item.key,name:item.displayName,selected:selected.map(String).includes(String(item._id))})),privateByDefault:true}})});searchRouter.put('/interests/me',async(req,res)=>{const input=z.object({interestIds:z.array(z.string().refine(Types.ObjectId.isValid)).max(30)}).strict().parse(req.body),valid=await Interest.find({_id:{$in:input.interestIds},active:true}).distinct('_id');await UserInterest.deleteMany({userId:req.user!.id});if(valid.length)await UserInterest.insertMany(valid.map(interestId=>({userId:req.user!.id,interestId,isPublic:false})));res.json({success:true,data:{selected:valid.map(String),privateByDefault:true}})});
searchRouter.get('/recommendations/people',async(req,res)=>{const blocked=await blockedIds(req.user!.id),following=await Follow.find({follower:req.user!.id,status:'accepted'}).distinct('following'),followers=await Follow.find({following:req.user!.id,status:'accepted'}).distinct('follower'),excluded=[req.user!.id,...following,...blocked],secondDegree=await Follow.find({follower:{$in:followers},status:'accepted',following:{$nin:excluded}}).select('following').lean(),mutual=new Map<string,number>();secondDegree.forEach(item=>mutual.set(String(item.following),(mutual.get(String(item.following))??0)+1));const candidates=await User.find({_id:{$nin:excluded},status:'active'}).select(userFields).sort({verified:-1,followersCount:-1,createdAt:-1}).limit(80).lean(),items=candidates.sort((a,b)=>(mutual.get(String(b._id))??0)-(mutual.get(String(a._id))??0)||b.followersCount-a.followersCount).slice(0,20).map(user=>({...mapUser(user as unknown as Record<string,unknown>),mutualFollowers:mutual.get(String(user._id))??0,reason:(mutual.get(String(user._id))??0)>0?'Followed by people in your network':'New on InstaFrame'}));res.json({success:true,data:{items,privacyNotice:'Recommendations use public profiles and follow graph only. Private messages, Final Notes and verification media are excluded.'}})});
searchRouter.get('/explore',async(req,res)=>{const since=new Date(Date.now()-30*86400000),following=await Follow.find({follower:req.user!.id,status:'accepted'}).distinct('following'),blocked=await blockedIds(req.user!.id);const [candidatePosts,candidateReels,trending,suggested]=await Promise.all([Post.find({visibility:'public',deletedAt:null,archivedAt:null,createdAt:{$gte:since},author:{$nin:blocked}}).sort({likesCount:-1,commentsCount:-1,createdAt:-1}).limit(120).populate('author',authorFields).lean(),Reel.find({visibility:'public',deletedAt:null,processingStatus:'ready',createdAt:{$gte:since},author:{$nin:blocked}}).sort({viewsCount:-1,watchTimeMs:-1,likesCount:-1}).limit(100).populate('author',authorFields).lean(),Hashtag.find({usageCount:{$gt:0}}).sort({usageCount:-1}).limit(12).lean(),User.find({_id:{$nin:[req.user!.id,...following,...blocked]},status:'active',allowProfileDiscovery:{$ne:false}}).select(userFields).sort({verified:-1,followersCount:-1,createdAt:-1}).limit(30).lean()]);const posts=diversifyByCreator(candidatePosts,item=>String((item.author as unknown as {_id:unknown})._id),36,2),reels=diverseRank(candidateReels,item=>Number(item.viewsCount)+Number(item.likesCount)*3+Number(item.commentsCount)*4,item=>String((item.author as unknown as {_id:unknown})._id),24,2);res.json({success:true,data:{posts:posts.map(item=>mapContent(item as unknown as Record<string,unknown>)),reels:reels.map(item=>mapContent(item as unknown as Record<string,unknown>)),hashtags:trending.map(item=>({name:item.displayTag??item.normalizedTag,count:item.usageCount})),suggestedUsers:suggested.slice(0,12).map(item=>mapUser(item as unknown as Record<string,unknown>))}})});
