import argon2 from 'argon2';import { Router } from 'express';import { isValidObjectId } from 'mongoose';import { requireAuth } from '../middleware/auth.js';import { AppError } from '../middleware/error.js';import { AccountDeletionJob,AuditLog,Block,Bookmark,Call,Comment,Conversation,Follow,Like,Message,Mute,Notification,Post,ProfilePhotoIndex,Reel,ReelBookmark,ReelLike,ReelView,Report,Session,User } from '../models/index.js';
export const settingsRouter=Router();settingsRouter.use(requireAuth);const publicFields='name username profilePhoto verified isPrivate allowPhotoDiscovery followersCount followingCount postsCount';
settingsRouter.get('/settings',async(req,res)=>{const user=await User.findById(req.user!.id).select('isPrivate allowProfileDiscovery allowPhotoDiscovery externalLinksVisibility privacy').lean();res.json({success:true,data:user})});
settingsRouter.get('/blocks',async(req,res)=>{const items=await Block.find({blocker:req.user!.id}).populate('blocked',publicFields).sort({createdAt:-1}).lean();res.json({success:true,data:{items:items.map(x=>({id:String(x._id),user:x.blocked}))}})});
settingsRouter.post('/blocks/:userId',async(req,res)=>{const id=req.params.userId;if(!isValidObjectId(id)||id===req.user!.id)throw new AppError(400,'INVALID_USER','Invalid user');if(!await User.exists({_id:id,status:'active'}))throw new AppError(404,'USER_NOT_FOUND','User not found');const accepted=await Follow.find({status:'accepted',$or:[{follower:req.user!.id,following:id},{follower:id,following:req.user!.id}]}).select('follower following').lean();await Block.updateOne({blocker:req.user!.id,blocked:id},{$setOnInsert:{blocker:req.user!.id,blocked:id}},{upsert:true});await Follow.deleteMany({$or:[{follower:req.user!.id,following:id},{follower:id,following:req.user!.id}]});await Promise.all(accepted.flatMap(item=>[User.findByIdAndUpdate(item.follower,{$inc:{followingCount:-1}}),User.findByIdAndUpdate(item.following,{$inc:{followersCount:-1}})]));res.status(201).json({success:true,data:{blocked:true}})});
settingsRouter.delete('/blocks/:userId',async(req,res)=>{await Block.deleteOne({blocker:req.user!.id,blocked:req.params.userId});res.json({success:true,data:{blocked:false}})});
settingsRouter.get('/mutes',async(req,res)=>{const items=await Mute.find({muter:req.user!.id}).populate('muted',publicFields).sort({createdAt:-1}).lean();res.json({success:true,data:{items:items.map(x=>({id:String(x._id),user:x.muted}))}})});
settingsRouter.post('/mutes/:userId',async(req,res)=>{const id=req.params.userId;if(!isValidObjectId(id)||id===req.user!.id)throw new AppError(400,'INVALID_USER','Invalid user');await Mute.updateOne({muter:req.user!.id,muted:id},{$setOnInsert:{muter:req.user!.id,muted:id}},{upsert:true});res.status(201).json({success:true,data:{muted:true}})});
settingsRouter.delete('/mutes/:userId',async(req,res)=>{await Mute.deleteOne({muter:req.user!.id,muted:req.params.userId});res.json({success:true,data:{muted:false}})});
settingsRouter.delete('/sessions/:sessionId',async(req,res)=>{if(!isValidObjectId(req.params.sessionId))throw new AppError(400,'INVALID_SESSION','Invalid session');const session=await Session.findOneAndUpdate({_id:req.params.sessionId,userId:req.user!.id,revokedAt:null},{$set:{revokedAt:new Date()}});if(!session)throw new AppError(404,'SESSION_NOT_FOUND','Session not found');res.json({success:true,data:null})});
settingsRouter.get('/account/export',async(req,res)=>{const id=req.user!.id;const [user,posts,reels,comments,follows,conversations,messages,calls,reports]=await Promise.all([User.findById(id).select('+email').lean(),Post.find({author:id}).lean(),Reel.find({author:id}).lean(),Comment.find({author:id}).lean(),Follow.find({$or:[{follower:id},{following:id}]}).lean(),Conversation.find({members:id}).lean(),Message.find({sender:id}).lean(),Call.find({$or:[{caller:id},{callee:id}]}).lean(),Report.find({reporter:id}).lean()]);res.setHeader('Content-Disposition','attachment; filename="instaframe-data.json"');res.json({success:true,data:{exportedAt:new Date().toISOString(),user,posts,reels,comments,follows,conversations,messages,calls,reports}})});
settingsRouter.post('/account/delete',async(req,res)=>{const password=String(req.body?.password??'').slice(0,128);const user=await User.findById(req.user!.id).select('+passwordHash');if(!user||!await argon2.verify(user.passwordHash,password))throw new AppError(401,'INVALID_PASSWORD','Password is incorrect');const [postAssets,reelAssets]=await Promise.all([Post.aggregate([{$match:{author:user._id}},{$unwind:'$media'},{$project:{_id:0,publicId:'$media.publicId',resourceType:'$media.resourceType'}}]),Reel.aggregate([{$match:{author:user._id}},{$project:{_id:0,publicId:'$video.publicId',resourceType:{$literal:'video'}}}])]) as [{publicId:string;resourceType:'image'|'video'}[],{publicId:string;resourceType:'video'}[]];const mediaAssets=[...postAssets,...reelAssets].filter(x=>x.publicId);await AccountDeletionJob.create({userId:user._id,mediaPublicIds:mediaAssets.map(x=>x.publicId),mediaAssets});const now=new Date();await Promise.all([ProfilePhotoIndex.deleteOne({userId:user._id}),Session.updateMany({userId:user._id,revokedAt:null},{$set:{revokedAt:now}}),Post.updateMany({author:user._id,deletedAt:null},{$set:{deletedAt:now}}),Reel.updateMany({author:user._id,deletedAt:null},{$set:{deletedAt:now}}),Comment.updateMany({author:user._id},{$set:{body:'',deletedAt:now}}),Follow.deleteMany({$or:[{follower:user._id},{following:user._id}]}),Block.deleteMany({$or:[{blocker:user._id},{blocked:user._id}]}),Mute.deleteMany({$or:[{muter:user._id},{muted:user._id}]}),Like.deleteMany({user:user._id}),Bookmark.deleteMany({user:user._id}),ReelLike.deleteMany({user:user._id}),ReelBookmark.deleteMany({user:user._id}),ReelView.deleteMany({user:user._id}),Notification.deleteMany({recipient:user._id}),AuditLog.create({actorId:user._id,action:'ACCOUNT_DELETED',targetType:'user',targetId:String(user._id)})]);user.status='deleted';user.name='Deleted member';const deletedId=String(user._id).slice(-22);user.username=`deleted_${deletedId}`;user.email=`deleted_${user._id}@invalid.local`;user.bio=undefined;user.profilePhoto=undefined;user.coverPhoto=undefined;user.socialLinks=undefined;user.allowPhotoDiscovery=false;user.allowProfileDiscovery=false;await user.save();res.json({success:true,data:{deleted:true,mediaCleanup:'queued'}})});

