import cookieParser from 'cookie-parser';
import cors from 'cors';
import express from 'express';
import { rateLimit } from 'express-rate-limit';
import helmet from 'helmet';
import { env } from './config/env.js';
import { distributedRateLimitStore } from './config/redis.js';
import { errorHandler, notFound } from './middleware/error.js';
import { sanitizeRequest } from './middleware/sanitize.js';
import { adminRouter } from './routes/admin.js';
import { adminSecureRouter } from './routes/adminSecure.js';
import authRoutes from './routes/auth.js';
import { callRouter } from './routes/calls.js';
import { cloudinaryWebhookHandler } from './routes/cloudinaryWebhook.js';
import { commentRouter } from './routes/comments.js';
import { router as coreRoutes } from './routes/core.js';
import { mediaOperationsRouter } from './routes/mediaOperations.js';
import { messageRouter } from './routes/messages.js';
import { notificationRouter } from './routes/notifications.js';
import { postRouter } from './routes/posts.js';
import { profileRouter } from './routes/profiles.js';
import { reelRouter } from './routes/reels.js';
import { reelUploadRouter } from './routes/reelUploads.js';
import { searchRouter } from './routes/search.js';
import { settingsRouter } from './routes/settings.js';
import { finalNoteRouter } from './routes/finalNotes.js';
import { storyRouter } from './routes/stories.js';
import { discoveryRouter } from './discovery/discovery.routes.js';
import { aiRouter } from './ai/ai.routes.js';
import { healthRouter,telemetryRouter } from './routes/telemetry.js';
import { billingRouter } from './routes/billing.js';
import { groupRouter } from './routes/groups.js';

export const app = express();
app.set('trust proxy', 1);
const skipRateLimit=()=>env.NODE_ENV==='test';
app.use(helmet());
const configuredOrigins=[env.CLIENT_URL,env.ADMIN_URL,env.MOBILE_APP_URL].filter((value):value is string=>Boolean(value));
const developmentOrigin=/^https?:\/\/(?:localhost|127\.0\.0\.1|10\.\d+\.\d+\.\d+|192\.168\.\d+\.\d+|172\.(?:1[6-9]|2\d|3[01])\.\d+\.\d+):\d+$/;
app.use(cors({origin(origin,callback){if(!origin||configuredOrigins.includes(origin)||(env.NODE_ENV==='development'&&developmentOrigin.test(origin)))return callback(null,true);return callback(new Error('Origin is not allowed by CORS'));},credentials:true}));
app.post('/api/webhooks/cloudinary', express.raw({ type: 'application/json', limit: '1mb' }), cloudinaryWebhookHandler);
app.use(express.json({ limit: '1mb' }));
app.use(cookieParser());
app.use(sanitizeRequest);
app.use('/api', rateLimit({ windowMs: 15 * 60_000, limit: 300,skip:skipRateLimit, standardHeaders: 'draft-8', legacyHeaders: false, passOnStoreError:true, ...(distributedRateLimitStore('api') ? { store: distributedRateLimitStore('api') } : {}) }));
app.use('/api/auth/login', rateLimit({ windowMs: 15 * 60_000, limit: 10,skip:skipRateLimit, passOnStoreError:true, ...(distributedRateLimitStore('login') ? { store: distributedRateLimitStore('login') } : {}) }));
app.use('/api/discovery/search', rateLimit({ windowMs: 60 * 60_000, limit: env.DISCOVERY_RATE_LIMIT_PER_HOUR, passOnStoreError:true, ...(distributedRateLimitStore('discovery') ? { store: distributedRateLimitStore('discovery') } : {}) }));
app.use('/api/discovery/scan',rateLimit({windowMs:60*60_000,limit:env.DISCOVERY_RATE_LIMIT_PER_HOUR,passOnStoreError:true,...(distributedRateLimitStore('discovery-scan')?{store:distributedRateLimitStore('discovery-scan')}:{})}));
app.use('/api/ai',rateLimit({windowMs:60*60_000,limit:env.AI_RATE_LIMIT_PER_HOUR,passOnStoreError:true,...(distributedRateLimitStore('ai')?{store:distributedRateLimitStore('ai')}:{})}));
app.use(['/api/follow-requests','/api/profiles'],rateLimit({windowMs:60_000,limit:120,standardHeaders:'draft-8',legacyHeaders:false,passOnStoreError:true,...(distributedRateLimitStore('social-graph')?{store:distributedRateLimitStore('social-graph')}:{})}));
app.use(['/api/conversations','/api/message-requests','/api/messages'],rateLimit({windowMs:60_000,limit:90,skip:skipRateLimit,standardHeaders:'draft-8',legacyHeaders:false,passOnStoreError:true,...(distributedRateLimitStore('messaging')?{store:distributedRateLimitStore('messaging')}:{})}));
app.use('/api/groups',rateLimit({windowMs:60_000,limit:90,skip:skipRateLimit,standardHeaders:'draft-8',legacyHeaders:false,passOnStoreError:true,...(distributedRateLimitStore('groups')?{store:distributedRateLimitStore('groups')}:{})}));
app.use('/api/stories',rateLimit({windowMs:60_000,limit:120,standardHeaders:'draft-8',legacyHeaders:false,passOnStoreError:true,...(distributedRateLimitStore('stories')?{store:distributedRateLimitStore('stories')}:{})}));
app.use('/api/reels',rateLimit({windowMs:60_000,limit:120,standardHeaders:'draft-8',legacyHeaders:false,passOnStoreError:true,...(distributedRateLimitStore('reels')?{store:distributedRateLimitStore('reels')}:{})}));
app.use('/api/final-notes',rateLimit({windowMs:60*60_000,limit:10,standardHeaders:'draft-8',legacyHeaders:false,passOnStoreError:true,...(distributedRateLimitStore('final-notes')?{store:distributedRateLimitStore('final-notes')}:{})}));
app.get('/health', (_req, res) => res.json({ success: true, data: { status: 'ok' } }));
app.use(healthRouter);
app.use('/api',rateLimit({windowMs:60_000,limit:60,skip:skipRateLimit,standardHeaders:'draft-8',legacyHeaders:false}),telemetryRouter);
app.use('/api/auth', authRoutes);
app.use('/api', profileRouter);
app.use('/api', postRouter);
app.use('/api', commentRouter);
app.use('/api', notificationRouter);
app.use('/api', messageRouter);
app.use('/api', callRouter);
app.use('/api', searchRouter);
app.use('/api', reelRouter);
app.use('/api', reelUploadRouter);
app.use('/api', settingsRouter);
app.use('/api', finalNoteRouter);
app.use('/api', storyRouter);
app.use('/api',discoveryRouter);
app.use('/api',aiRouter);
app.use('/api',billingRouter);
app.use('/api',groupRouter);
app.use('/api', mediaOperationsRouter);
app.use('/api', adminRouter);
app.use('/api', adminSecureRouter);
app.use('/api', coreRoutes);
app.use(notFound);
app.use(errorHandler);
