import type { CallDto, ConversationDto, IceConfig, PublicProfile } from '@instaframe/contracts';
import { Camera, CameraOff, LoaderCircle, Mic, MicOff, Phone, PhoneCall, PhoneOff, Search, Video } from 'lucide-react';
import { useCallback, useEffect, useRef, useState } from 'react';
import { useAuth } from '../auth/AuthContext';
import { api, ApiError } from '../lib/api';
import { getSocket } from '../lib/socket';

type Person = PublicProfile & { _id?: string };
type Active = { record: CallDto; peer: PublicProfile; state: 'calling' | 'incoming' | 'connecting' | 'connected'; offer?: RTCSessionDescriptionInit };
const person = (value: Person): PublicProfile => ({ ...value, id: value.id ?? value._id ?? '' });
const callPerson = (value: PublicProfile & { _id?: string }) => person(value);

export function Calls() {
  const { user } = useAuth();
  const [history, setHistory] = useState<CallDto[]>([]), [contacts, setContacts] = useState<PublicProfile[]>([]), [results, setResults] = useState<PublicProfile[]>([]), [query, setQuery] = useState(''), [active, setActive] = useState<Active>(), [error, setError] = useState(''), [muted, setMuted] = useState(false), [cameraOff, setCameraOff] = useState(false);
  const activeRef = useRef<Active | undefined>(undefined), localVideo = useRef<HTMLVideoElement>(null), remoteVideo = useRef<HTMLVideoElement>(null), localStream = useRef<MediaStream | undefined>(undefined), connection = useRef<RTCPeerConnection | undefined>(undefined), ice = useRef<IceConfig | undefined>(undefined), pendingIce = useRef<RTCIceCandidateInit[]>([]);
  useEffect(() => { activeRef.current = active; }, [active]);
  const normalizeCall = (call: CallDto): CallDto => ({ ...call, caller: callPerson(call.caller as Person), callee: callPerson(call.callee as Person) });
  const load = useCallback(async () => { try { const [calls, chats, config] = await Promise.all([api<{ items: CallDto[] }>('/api/calls'), api<{ items: ConversationDto[] }>('/api/conversations'), api<IceConfig>('/api/calls/config')]); setHistory(calls.items.map(normalizeCall)); const people = chats.items.filter(item => item.type === 'direct').flatMap(item => item.members.map(value => person(value as Person)).filter(value => value.id && value.id !== user?.id)); setContacts([...new Map(people.map(value => [value.id, value])).values()]); ice.current = config; } catch (cause) { setError(cause instanceof ApiError ? cause.message : 'Could not load calling'); } }, [user?.id]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { if (query.trim().length < 2) { setResults([]); return; } const timer = setTimeout(() => api<{ users: Person[] }>(`/api/search?q=${encodeURIComponent(query)}&type=people`).then(data => setResults(data.users.map(person).filter(value => value.id))).catch(() => setResults([])), 300); return () => clearTimeout(timer); }, [query]);
  const media = async (kind: 'audio' | 'video') => { if (!navigator.mediaDevices?.getUserMedia) throw new Error('This browser does not support camera or microphone calling'); const stream = await navigator.mediaDevices.getUserMedia({ audio: true, video: kind === 'video' ? { width: { ideal: 1280 }, height: { ideal: 720 }, facingMode: 'user' } : false }); localStream.current = stream; queueMicrotask(() => { if (localVideo.current) localVideo.current.srcObject = stream; }); return stream; };
  const cleanup = () => { connection.current?.close(); connection.current = undefined; localStream.current?.getTracks().forEach(track => track.stop()); localStream.current = undefined; pendingIce.current = []; setMuted(false); setCameraOff(false); };
  const finish = useCallback(async (status: 'ended' | 'rejected' | 'failed' = 'ended') => { const current = activeRef.current; if (!current) return; getSocket().emit(status === 'rejected' ? 'call:reject' : 'call:end', { callId: current.record.id, recipientId: current.peer.id }); try { await api(`/api/calls/${current.record.id}`, { method: 'PATCH', body: JSON.stringify({ status }) }); } catch { /* already ended */ } cleanup(); activeRef.current = undefined; setActive(undefined); void load(); }, [load]);
  const makePeer = (callId: string, recipientId: string) => { const pc = new RTCPeerConnection(ice.current); connection.current = pc; pc.ontrack = event => { if (remoteVideo.current) remoteVideo.current.srcObject = event.streams[0] ?? new MediaStream([event.track]); }; pc.onicecandidate = event => { if (event.candidate) getSocket().emit('call:ice-candidate', { callId, recipientId, payload: event.candidate.toJSON() }); }; pc.onconnectionstatechange = () => { if (pc.connectionState === 'connected') { setActive(current => current ? { ...current, state: 'connected' } : current); void api(`/api/calls/${callId}`, { method: 'PATCH', body: JSON.stringify({ status: 'active' }) }).catch(() => undefined); } if (pc.connectionState === 'failed') void finish('failed'); }; return pc; };
  const start = async (target: PublicProfile, kind: 'audio' | 'video') => { if (!target.id) { setError('Contact ID is unavailable. Refresh and try again.'); return; } setError(''); try { const eligibility = await api<{ eligible: boolean; message?: string }>(`/api/calls/eligibility/${target.id}?kind=${kind}`); if (!eligibility.eligible) throw new Error(eligibility.message ?? 'This member cannot receive your call'); const record = normalizeCall(await api<CallDto>('/api/calls', { method: 'POST', body: JSON.stringify({ calleeId: target.id, kind }) })); const current: Active = { record, peer: target, state: 'calling' }; activeRef.current = current; setActive(current); const stream = await media(kind), pc = makePeer(record.id, target.id); stream.getTracks().forEach(track => pc.addTrack(track, stream)); const offer = await pc.createOffer(); await pc.setLocalDescription(offer); getSocket().emit('call:offer', { callId: record.id, recipientId: target.id, payload: offer }); } catch (cause) { cleanup(); setActive(undefined); activeRef.current = undefined; setError(cause instanceof Error ? cause.message : 'Could not start call'); } };
  const accept = async () => { const current = activeRef.current; if (!current?.offer) return; try { await api(`/api/calls/${current.record.id}`, { method: 'PATCH', body: JSON.stringify({ status: 'accepted' }) }); const stream = await media(current.record.kind), pc = makePeer(current.record.id, current.peer.id); stream.getTracks().forEach(track => pc.addTrack(track, stream)); await pc.setRemoteDescription(current.offer); for (const candidate of pendingIce.current.splice(0)) await pc.addIceCandidate(candidate); const answer = await pc.createAnswer(); await pc.setLocalDescription(answer); getSocket().emit('call:answer', { callId: current.record.id, recipientId: current.peer.id, payload: answer }); setActive({ ...current, state: 'connecting' }); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not accept call'); } };
  useEffect(() => { const socket = getSocket(); const offer = async (data: { callId: string; payload: RTCSessionDescriptionInit }) => { const calls = await api<{ items: CallDto[] }>('/api/calls'), record = calls.items.map(normalizeCall).find(item => item.id === data.callId); if (record) { const current: Active = { record, peer: record.caller, state: 'incoming', offer: data.payload }; activeRef.current = current; setActive(current); } }; const answer = async (data: { callId: string; payload: RTCSessionDescriptionInit }) => { if (activeRef.current?.record.id === data.callId && connection.current) { await connection.current.setRemoteDescription(data.payload); for (const candidate of pendingIce.current.splice(0)) await connection.current.addIceCandidate(candidate); setActive(current => current ? { ...current, state: 'connecting' } : current); } }; const candidate = (data: { callId: string; payload: RTCIceCandidateInit }) => { if (activeRef.current?.record.id !== data.callId) return; if (connection.current?.remoteDescription) void connection.current.addIceCandidate(data.payload); else pendingIce.current.push(data.payload); }; const ended = (data: { callId: string }) => { if (activeRef.current?.record.id === data.callId) { cleanup(); activeRef.current = undefined; setActive(undefined); void load(); } }; socket.on('call:offer', offer); socket.on('call:answer', answer); socket.on('call:ice-candidate', candidate); socket.on('call:reject', ended); socket.on('call:end', ended); return () => { socket.off('call:offer', offer); socket.off('call:answer', answer); socket.off('call:ice-candidate', candidate); socket.off('call:reject', ended); socket.off('call:end', ended); }; }, [load]);
  const toggleMic = () => { const next = !muted; localStream.current?.getAudioTracks().forEach(track => { track.enabled = !next; }); setMuted(next); }, toggleCamera = () => { const next = !cameraOff; localStream.current?.getVideoTracks().forEach(track => { track.enabled = !next; }); setCameraOff(next); }, other = (call: CallDto) => call.caller.id === user?.id ? call.callee : call.caller, available = results.length ? results : contacts;
  return <div className="calls-page"><header><div><p className="eyebrow">PRIVATE WEBRTC CALLING</p><h1>Calls</h1><p>Search an eligible InstaFrame contact and start an audio or video call.</p></div></header>{error && <p className="form-error">{error}</p>}<section className="call-contacts"><h2>Start a call</h2><label className="conversation-search"><Search/><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search by name or username"/></label>{available.map(target => <article key={target.id}><span className="chat-avatar">{target.profilePhoto ? <img src={target.profilePhoto} alt=""/> : target.name[0]}</span><div><b>{target.name}</b><small>@{target.username}</small></div><button onClick={() => void start(target, 'audio')} aria-label={`Audio call ${target.name}`}><Phone/></button><button onClick={() => void start(target, 'video')} aria-label={`Video call ${target.name}`}><Video/></button></article>)}{!available.length && <p className="muted">Search an eligible member to call.</p>}</section><section className="call-history"><h2>Recent calls</h2>{history.map(call => <article key={call.id}><span className={`call-status ${call.status}`}><PhoneCall/></span><div><b>{other(call).name}</b><small>{call.kind} · {call.status} · {new Date(call.startedAt).toLocaleString()}</small></div></article>)}</section>{active && <div className="call-overlay"><div className="remote-stage">{active.record.kind === 'video' ? <video ref={remoteVideo} autoPlay playsInline/> : <div className="caller-orb">{active.peer.name[0]}</div>}<video ref={localVideo} autoPlay playsInline muted className="local-video"/><div className="call-copy"><small>{active.state}</small><h2>{active.peer.name}</h2><p>{active.record.kind} call</p></div>{active.state === 'connecting' && <LoaderCircle className="spin connecting"/>}</div><div className="call-controls">{active.state === 'incoming' ? <><button className="accept" onClick={() => void accept()}><Phone/></button><button className="hangup" onClick={() => void finish('rejected')}><PhoneOff/></button></> : <><button onClick={toggleMic}>{muted ? <MicOff/> : <Mic/>}</button>{active.record.kind === 'video' && <button onClick={toggleCamera}>{cameraOff ? <CameraOff/> : <Camera/>}</button>}<button className="hangup" onClick={() => void finish()}><PhoneOff/></button></>}</div></div>}</div>;
}
