import { Link } from 'react-router-dom';

type LegalKey='privacy'|'terms'|'community-guidelines'|'copyright'|'data-policy';
const content:Record<LegalKey,{title:string;intro:string;sections:[string,string][]}>={
  privacy:{title:'Privacy Policy',intro:'InstaFrame is designed around consent, user control and data minimization.',sections:[['Information we process','We process account information, profile details, content and activity needed to provide features you choose to use. Login email, security records, verification material and private activity are not public profile fields.'],['Photo discovery','Photo discovery is off by default and searches only approved photos belonging to active members who opted in. It does not search the internet or identify non-members. Disabling discovery removes the profile from future matching and queues index data for deletion.'],['Private communication','Private messages, One Final Notes, verification documents and call media are not automatically sent to AI providers. Blocking cannot be bypassed through messaging, calls, search or discovery.'],['Your controls','You can edit privacy settings, revoke sessions, download your data and delete your account. Deletion invalidates sessions, removes discovery indexing, hides content and queues media cleanup.']]},
  terms:{title:'Terms of Use',intro:'Use InstaFrame responsibly and respect other members.',sections:[['Account responsibility','Provide accurate registration information, protect your credentials and use only accounts you are authorized to control.'],['Acceptable use','Do not harass, impersonate, defraud, scrape, automate bulk discovery, evade blocks or attempt to identify non-consenting people.'],['Content and AI','You are responsible for content you publish. AI suggestions may be inaccurate, require your explicit request and are never auto-published.'],['Enforcement','Reports are reviewed and important moderation actions are audited. Accounts or content may be restricted when rules or law require it.']]},
  'community-guidelines':{title:'Community Guidelines',intro:'Keep InstaFrame safe, authentic and welcoming.',sections:[['Respect people','Do not share harassment, credible threats, exploitation, hateful abuse or non-consensual intimate content. Respect privacy settings and blocks.'],['Be authentic','Do not impersonate people, coordinate scams, manipulate engagement or misrepresent verification.'],['Share safely','Post media you have a right to use. Report concerning content rather than amplifying it.'],['Discovery boundaries','InstaFrame Scan is opt-in member discovery, not public facial identification. Surveillance and bulk scanning are prohibited.']]},
  copyright:{title:'Copyright',intro:'Share only media you own or have permission to use.',sections:[['Your responsibility','Upload content you created, licensed or are otherwise permitted to share. Audio overlays must be user-owned or properly licensed.'],['Report infringement','Use the report flow and select Copyright. Include enough information for responsible review.'],['Review','Moderators may remove reported content after review. Where supported, affected users can provide context or appeal incorrect decisions.']]},
  'data-policy':{title:'Data Policy',intro:'How storage, processing and retention work.',sections:[['Storage','MongoDB stores application records and Cloudinary stores media. Provider credentials remain on trusted servers.'],['Processing','Data is processed to authenticate users, enforce privacy, deliver requested features, prevent abuse and provide notifications.'],['Sensitive data','Passwords are hashed. Secrets and discovery vectors are protected and never exposed through normal APIs or moderation dashboards.'],['Retention','Temporary scan images are not retained unnecessarily. Operational records are deleted according to configured retention jobs and legal requirements.']]},
};
export function Legal({kind}:{kind:LegalKey}){const page=content[kind];return <main className="legal-page"><Link className="legal-brand" to="/">InstaFrame</Link><p className="eyebrow">LEGAL & TRUST</p><h1>{page.title}</h1><p className="legal-date">Effective 13 August 2026 · Product policy summary</p><p className="legal-intro">{page.intro}</p><nav>{Object.entries(content).map(([key,value])=><Link key={key} className={key===kind?'active':''} to={`/${key}`}>{value.title.replace(' Policy','')}</Link>)}</nav><section>{page.sections.map(([title,body],index)=><article key={title}><span>{String(index+1).padStart(2,'0')}</span><div><h2>{title}</h2><p>{body}</p></div></article>)}</section><aside><b>Important</b><p>InstaFrame is not an identity-verification authority. Photo matches involving opted-in members are suggestions, not proof of identity.</p></aside></main>}
